### ISSUE TITLE
Getting Error of Unexpected token

### ISSUE THREAD

**Issue by munjalpandya** [CuppaLabs/angular2-datetimepicker#25]
I am getting below error when I run my app after including the datetime picker. Is there any changes to be done in systemjs file?

### Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:54199/app/app.module.js:47:33)
	    at eval (http://localhost:54199/app/app.module.js:81:4)
	    at eval (http://localhost:54199/app/app.module.js:82:3)
	Evaluating http://localhost:54199/angular2-datetimepicker
	Evaluating http://localhost:54199/app/app.module.js
	Evaluating http://localhost:54199/app/main.js
	Error loading http://localhost:54199/app/main.js
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:54199/app/app.module.js:47:33)
	    at eval (http://localhost:54199/app/app.module.js:81:4)
	    at eval (http://localhost:54199/app/app.module.js:82:3)
	Evaluating http://localhost:54199/angular2-datetimepicker
	Evaluating http://localhost:54199/app/app.module.js
	Evaluating http://localhost:54199/app/main.js
	Error loading http://localhost:54199/app/main.js

Please let me know the solution to this.

**Comment by munjalpandya** [comment]
I sorted out the issue myseld. Entry in systemjs file was not done.

Thanks.
